version: "3.7"
services:
  purchase:
    image: purchases:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresPurchases
    restart: always

