version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresPurchases
    restart: always

  purchase:
    image: purchases:latest
    container_name: purchase
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

